import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const events = [
  // ========== 台灣賽事（真實資料，來源：運動筆記 running.biji.co）==========
  {
    name: "2026 新北市萬金石馬拉松",
    region: "taiwan",
    city: "新北",
    date: new Date("2026-03-15"),
    registrationStart: new Date("2025-10-17"),
    registrationEnd: new Date("2025-10-30"),
    distances: JSON.stringify(["全馬 42.195K", "10K"]),
    status: "closed",
    websiteUrl: "https://www.wanjinshi-marathon.com.tw/",
    sourceUrl: "https://running.biji.co/index.php?q=competition&act=info&cid=12771",
    source: "running.biji.co",
    description: "World Athletics 金標賽事，沿北海岸路線，全馬限額 6,500 人，報名費 NT$1,500。已於 2026/3/15 完賽。",
    featured: true,
    verified: true,
  },
  {
    name: "2026 金門馬拉松",
    region: "taiwan",
    city: "金門",
    date: new Date("2026-01-24"),
    registrationStart: new Date("2025-07-23"),
    registrationEnd: new Date("2025-12-12"),
    distances: JSON.stringify(["全馬 42.195K", "半馬 21K", "10K", "4K"]),
    status: "closed",
    sourceUrl: "https://running.biji.co/index.php?q=competition&act=info&cid=12628",
    source: "running.biji.co",
    description: "金門縣政府主辦，完賽贈品含金門高粱酒紀念瓷瓶。全馬限額 2,000 人，半馬 3,300 人。已於 2026/1/24-25 完賽。",
    verified: true,
  },
  {
    name: "2026 TS WOMEN RUN 台新新光女子路跑",
    region: "taiwan",
    city: "台北",
    date: new Date("2026-04-12"),
    registrationStart: new Date("2025-11-25"),
    registrationEnd: new Date("2026-02-25"),
    distances: JSON.stringify(["半馬 21K", "10K", "3K"]),
    status: "closed",
    sourceUrl: "https://running.biji.co/index.php?q=competition&act=info&cid=12827",
    source: "running.biji.co",
    description: "限女性參加的路跑賽事，起點臺北市政府市民廣場，半馬限額 6,000 人，報名費 NT$1,400。",
    verified: true,
  },
  {
    name: "2026 光境半程馬拉松挑戰賽-升龍道",
    region: "taiwan",
    city: "新北",
    date: new Date("2026-04-19"),
    registrationStart: new Date("2025-12-02"),
    registrationEnd: new Date("2026-03-06"),
    distances: JSON.stringify(["半馬 21K", "13K"]),
    status: "closed",
    sourceUrl: "https://running.biji.co/index.php?q=competition&act=info&cid=12835",
    source: "running.biji.co",
    description: "龍巖主辦，從富貴角停車場出發的越野半馬，個人組報名費 NT$1,500，限額 600 人，限時 4.5 小時。",
    verified: true,
  },
  {
    name: "2026 國家地理路跑 RUN FOR EARTH",
    region: "taiwan",
    city: "台北",
    date: new Date("2026-04-26"),
    registrationStart: new Date("2025-11-13"),
    registrationEnd: new Date("2026-03-05"),
    distances: JSON.stringify(["半馬 21K", "10K", "5K"]),
    status: "closed",
    sourceUrl: "https://running.biji.co/index.php?q=competition&act=info&cid=12725",
    source: "running.biji.co",
    description: "台灣華特迪士尼主辦，起點臺北市政府，半馬限額 5,000 人，報名費 NT$1,390。",
    featured: true,
    verified: true,
  },
  {
    name: "2026 新竹半程馬拉松",
    region: "taiwan",
    city: "新竹",
    date: new Date("2026-04-12"),
    registrationStart: new Date("2025-12-26"),
    registrationEnd: new Date("2026-01-27"),
    distances: JSON.stringify(["半馬 21K", "10K", "5.5K"]),
    status: "closed",
    sourceUrl: "https://running.biji.co/index.php?q=competition&act=info&cid=12871",
    source: "running.biji.co",
    description: "新竹縣體育場出發，半馬報名費 NT$1,180，限時 3 小時 30 分。",
    verified: true,
  },
  {
    name: "2026 木棉花道超半程馬拉松",
    region: "taiwan",
    city: "台南",
    date: new Date("2026-03-29"),
    registrationStart: new Date("2025-10-01"),
    registrationEnd: new Date("2026-02-01"),
    distances: JSON.stringify(["半馬 21K", "11K", "4K"]),
    status: "closed",
    sourceUrl: "https://running.biji.co/index.php?q=competition&act=info&cid=12572",
    source: "running.biji.co",
    description: "花開白河・RUN出英雄道，臺南白河運動公園出發，半馬限額 700 人，報名費 NT$1,100。",
    verified: true,
  },
  {
    name: "2026 臺南古都國際半程馬拉松",
    region: "taiwan",
    city: "台南",
    date: new Date("2026-03-01"),
    distances: JSON.stringify(["半馬 21K"]),
    status: "closed",
    sourceUrl: "https://running.biji.co/index.php?q=competition&act=info&cid=12640",
    source: "running.biji.co",
    description: "年度台南古都半馬，已於 2026/3/1 完賽，相簿超過 46,000 張照片。",
    verified: true,
  },
  {
    name: "2026 臺中城市半程馬拉松 RUN FOR OUR PLANET",
    region: "taiwan",
    city: "台中",
    date: new Date("2026-03-15"),
    distances: JSON.stringify(["半馬 21K"]),
    status: "closed",
    sourceUrl: "https://running.biji.co/index.php?q=competition&act=info&cid=12608",
    source: "running.biji.co",
    description: "2026 年臺中城市半馬，已於 2026/3/15 完賽，相簿超過 70,000 張照片。",
    verified: true,
  },
  {
    name: "2026 海風馬拉松",
    region: "taiwan",
    city: "台灣",
    date: new Date("2026-03-22"),
    registrationEnd: new Date("2026-01-23"),
    distances: JSON.stringify(["半馬 21K"]),
    status: "closed",
    sourceUrl: "https://running.biji.co/index.php?q=competition&act=info&cid=12833",
    source: "running.biji.co",
    description: "2026 海風馬拉松，已於 2026/3/22 完賽。",
    verified: true,
  },

  // ========== 國際賽事（真實資料，來源：World Athletics / worldmarathonmajors.com）==========
  {
    name: "2026 Tokyo Marathon 東京馬拉松",
    nameEn: "Tokyo Marathon",
    region: "international",
    country: "日本",
    city: "東京",
    date: new Date("2026-03-01"),
    distances: JSON.stringify(["全馬 42.195K", "10K"]),
    status: "closed",
    websiteUrl: "https://www.marathon.tokyo/en/",
    source: "worldathletics.org",
    description: "世界六大馬拉松之一，World Athletics 白金標賽事。2026 年已於 3/1 完賽。",
    featured: true,
    verified: true,
  },
  {
    name: "2026 Boston Marathon 波士頓馬拉松",
    nameEn: "Boston Marathon",
    region: "international",
    country: "美國",
    city: "波士頓",
    date: new Date("2026-04-20"),
    distances: JSON.stringify(["全馬 42.195K"]),
    status: "closed",
    websiteUrl: "https://www.baa.org/races/boston-marathon",
    source: "worldmarathonmajors.com",
    description: "世界最古老的年度馬拉松（始於 1897 年），需達 BQ 資格。2026 年 4/20 舉行。",
    featured: true,
    verified: true,
  },
  {
    name: "2026 London Marathon 倫敦馬拉松",
    nameEn: "London Marathon",
    region: "international",
    country: "英國",
    city: "倫敦",
    date: new Date("2026-04-26"),
    distances: JSON.stringify(["全馬 42.195K"]),
    status: "closed",
    websiteUrl: "https://www.tcslondonmarathon.com/",
    source: "worldmarathonmajors.com",
    description: "世界六大馬拉松之一，2026 年精英選手包括 Sawe、Kiplimo、Assefa、Hassan 等。4/26 舉行。",
    featured: true,
    verified: true,
  },
  {
    name: "2026 Berlin Marathon 柏林馬拉松",
    nameEn: "Berlin Marathon",
    region: "international",
    country: "德國",
    city: "柏林",
    date: new Date("2026-09-27"),
    distances: JSON.stringify(["全馬 42.195K"]),
    status: "upcoming",
    websiteUrl: "https://www.bmw-berlin-marathon.com/en/",
    source: "worldmarathonmajors.com",
    description: "世界六大馬拉松之一，平坦快速賽道，世界紀錄多次在此誕生。2026/9/27 舉行。",
    featured: true,
    verified: true,
  },
  {
    name: "2026 Chicago Marathon 芝加哥馬拉松",
    nameEn: "Chicago Marathon",
    region: "international",
    country: "美國",
    city: "芝加哥",
    date: new Date("2026-10-11"),
    distances: JSON.stringify(["全馬 42.195K"]),
    status: "upcoming",
    websiteUrl: "https://www.chicagomarathon.com/",
    source: "worldmarathonmajors.com",
    description: "世界六大馬拉松之一，快速平坦的城市賽道。2026/10/11 舉行。",
    featured: true,
    verified: true,
  },
  {
    name: "2026 New York City Marathon 紐約馬拉松",
    nameEn: "New York City Marathon",
    region: "international",
    country: "美國",
    city: "紐約",
    date: new Date("2026-11-01"),
    distances: JSON.stringify(["全馬 42.195K"]),
    status: "upcoming",
    websiteUrl: "https://www.nyrr.org/tcsnycmarathon",
    source: "worldmarathonmajors.com",
    description: "世界六大馬拉松之一，穿越紐約五大區，世界最大規模馬拉松。2026/11/1 舉行。",
    featured: true,
    verified: true,
  },
  {
    name: "2026 Seoul Marathon 首爾馬拉松",
    nameEn: "Seoul Marathon",
    region: "international",
    country: "韓國",
    city: "首爾",
    date: new Date("2026-03-15"),
    distances: JSON.stringify(["全馬 42.195K", "10K"]),
    status: "closed",
    websiteUrl: "https://www.seoul-marathon.com/",
    source: "worldathletics.org",
    description: "World Athletics 金標賽事，2026/3/15 舉行。已完賽。",
    verified: true,
  },
  {
    name: "2026 Barcelona Marathon 巴塞隆納馬拉松",
    nameEn: "Zurich Marató de Barcelona",
    region: "international",
    country: "西班牙",
    city: "巴塞隆納",
    date: new Date("2026-03-15"),
    distances: JSON.stringify(["全馬 42.195K"]),
    status: "closed",
    source: "worldathletics.org",
    description: "2026/3/15 舉行，Tesfay 以 2:10:51 創下出道紀錄。",
    verified: true,
  },
  {
    name: "2026 Nagoya Women's Marathon 名古屋女子馬拉松",
    nameEn: "Nagoya Women's Marathon",
    region: "international",
    country: "日本",
    city: "名古屋",
    date: new Date("2026-03-08"),
    distances: JSON.stringify(["全馬 42.195K"]),
    status: "closed",
    source: "worldathletics.org",
    description: "世界最大女子馬拉松之一，2026/3/8 舉行，Chepkirui 衛冕成功。",
    verified: true,
  },
  {
    name: "2026 Gold Coast Marathon 黃金海岸馬拉松",
    nameEn: "Gold Coast Marathon",
    region: "international",
    country: "澳洲",
    city: "黃金海岸",
    date: new Date("2026-07-05"),
    distances: JSON.stringify(["全馬 42.195K", "半馬 21K", "10K", "5K"]),
    status: "upcoming",
    websiteUrl: "https://goldcoastmarathon.com.au/",
    source: "worldmarathonmajors.com",
    description: "澳洲最平坦快速的馬拉松，沿海岸線奔跑。2026/7/5 舉行。",
    verified: true,
  },
  {
    name: "2026 Osaka Marathon 大阪馬拉松",
    nameEn: "Osaka Marathon",
    region: "international",
    country: "日本",
    city: "大阪",
    date: new Date("2026-02-22"),
    distances: JSON.stringify(["全馬 42.195K"]),
    status: "closed",
    source: "worldathletics.org",
    description: "World Athletics 標籤賽事，2026/2/22 舉行。已完賽。",
    verified: true,
  },
  {
    name: "2026 Standard Chartered Hong Kong Marathon 香港馬拉松",
    nameEn: "Hong Kong Marathon",
    region: "international",
    country: "香港",
    city: "香港",
    date: new Date("2026-01-18"),
    distances: JSON.stringify(["全馬 42.195K", "半馬 21K", "10K"]),
    status: "closed",
    source: "worldathletics.org",
    description: "渣打香港馬拉松，World Athletics 標籤賽事，2026/1/18 舉行。已完賽。",
    verified: true,
  },
  {
    name: "2026 Wan Jin Shi Marathon 新北市萬金石馬拉松（國際）",
    nameEn: "New Taipei City Wan Jin Shi Marathon",
    region: "international",
    country: "台灣",
    city: "新北",
    date: new Date("2026-03-15"),
    distances: JSON.stringify(["全馬 42.195K", "10K"]),
    status: "closed",
    source: "worldathletics.org",
    description: "World Athletics 金標賽事，台灣唯一獲得 World Athletics 標籤的馬拉松。2026/3/15 舉行。已完賽。",
    verified: true,
  },
];

async function main() {
  console.log("🌱 Seeding with REAL data...");

  await prisma.event.deleteMany();

  for (const event of events) {
    await prisma.event.create({ data: event });
  }

  console.log(`✅ Seeded ${events.length} events (all verified from real sources)`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
